#!/usr/bin/dash
# Initram Root FS and Kernel Signing Utility
#
# System Management Daemon
#
# Copyright (C) 2016 - 2022 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

if [ $# -eq 0 ]; then
    find /boot -type f \( -name 'vmlinuz-*' -o -iname '*.efi' \) -exec "$0" {} \;
    exit 0
fi

if ! [ -f "$1" ]; then
    echo "File \"$1\" does not exist!"
    exit 1
fi

if ! sbverify --list "$1" 2>/dev/null | grep -q "signature certificates"; then
    sbsign --key "/opt/secureboot/db.key" --cert "/opt/secureboot/db.crt" --output "$1" "$1" | grep -v 'gaps between PE/COFF sections'
fi
