################################
### iDigitalFlame  2016-2026 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
## Mkinitcpio Configuration
#
# Copyright (C) 2016 - 2026 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

HOOKS=(systemd keyboard autodetect microcode modconf kms sd-vconsole block sd-encrypt lvm2 custom btrfs filesystems)
MODULES=(intel_agp i915 tpm tpm_tis usbhid intel_hid sparse_keymap)
BINARIES=(btrfs)
COMPRESSION="zstd"
MODULES_DECOMPRESS="yes"
COMPRESSION_OPTIONS=(-T0 -7 --long --asyncio --sparse)

FILES=(
    /usr/bin/btrfs
    /etc/vconsole.conf
    /etc/modprobe.d/wifi.conf
    /etc/modprobe.d/audio.conf
    /etc/modprobe.d/block.conf
    /etc/modprobe.d/video.conf
    /opt/spaceport/etc/vconsole.conf
    /opt/spaceport/etc/modprobe.d/wifi.conf
    /opt/spaceport/etc/modprobe.d/audio.conf
    /opt/spaceport/etc/modprobe.d/block.conf
    /opt/spaceport/etc/modprobe.d/video.conf
)
