################################
### iDigitalFlame  2016-2026 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
## SystemD Journal Configuration
#
# Copyright (C) 2016 - 2026 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

[Journal]
Seal                 = yes
Audit                = yes
LineMax              = 48K
Storage              = persistent
TTYPath              = /dev/console
Compress             = yes
ReadKMsg             = yes
SplitMode            = uid
MaxFileSec           = 1day
MaxLevelKMsg         = notice
MaxLevelWall         = emerg
SystemMaxUse         = 256M
ForwardToKMsg        = no
ForwardToWall        = no
MaxLevelStore        = info
MaxLevelSocket       = info
MaxLevelSyslog       = info
RateLimitBurst       = 10000
SystemMaxFiles       = 128
ForwardToSyslog      = no
MaxLevelConsole      = warning
MaxRetentionSec      = 14day
RuntimeMaxFiles      = 128
SyncIntervalSec      = 5m
ForwardToConsole     = no
SystemMaxFileSize    = 32M
RuntimeMaxFileSize   = 64M
RateLimitIntervalSec = 30s
