################################
### iDigitalFlame  2016-2025 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
## SystemD Configuration
#
# Copyright (C) 2016 - 2025 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

[Manager]
LogTime                           = no
DumpCore                          = no
LogColor                          = yes
LogLevel                          = warning
LogTarget                         = journal-or-kmsg
CrashShell                        = no
NUMAPolicy                        = default
ShowStatus                        = auto
CrashAction                       = freeze
LogLocation                       = no
CrashChangeVT                     = no
ProtectSystem                     = auto
DefaultTasksMax                   = 15%
NoNewPrivileges                   = no
DefaultOOMPolicy                  = stop
KExecWatchdogSec                  = off
StatusUnitFormat                  = description
DefaultRestartSec                 = 100ms
RebootWatchdogSec                 = 0
DefaultLimitNOFILE                = 1024:524288
RuntimeWatchdogSec                = off
DefaultIOAccounting               = no
DefaultIPAccounting               = no
DefaultLimitMEMLOCK               = 8M
ShutdownWatchdogSec               = 0
DefaultCPUAccounting              = no
DefaultStandardError              = inherit
CtrlAltDelBurstAction             = reboot-force
DefaultStandardOutput             = journal
DefaultTimeoutStopSec             = 15s
RuntimeWatchdogPreSec             = off
DefaultStartLimitBurst            = 5
DefaultTasksAccounting            = yes
DefaultTimeoutAbortSec            = 15s
DefaultTimeoutStartSec            = 15s
DefaultDeviceTimeoutSec           = 30s
DefaultMemoryAccounting           = yes
DefaultTimerAccuracySec           = 1min
SystemCallArchitectures           = native
DefaultBlockIOAccounting          = no
DefaultMemoryPressureWatch        = auto
DefaultStartLimitIntervalSec      = 10s
DefaultMemoryPressureThresholdSec = 200ms
