#!/usr/bin/bash
# smd-power-low
#  Script used by udev to inform the System Management Daemon that the battery power is low or near empty.
#  Should only be called by udev. Exit code is always 0.
#
# System Management Daemon
#
# Copyright (C) 2016 - 2021 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

/usr/lib/smd/libexec/smd-message -u notify -p "{\"title\": \"Battery is Low\", \"body\": \"Battery $1 power level is low!\", \"icon\": \"battery\"}"
exit 0
