#!/usr/bin/dash
################################
### iDigitalFlame  2016-2025 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
#
# Copyright (C) 2016 - 2025 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# smd-usb-add
#   Script used by Udev to inform SMD that a USB device was attached.
#   Can only be called by Udev.

if [ "$1" = "" ] || [ "$2" = "" ]; then
    exit 0
fi

if [ "$1" = "0bda" ] || [ "$1" = "1050" ]; then
    # Ignore Dell Devices as the Dock can trigger a false positive.
    # Also ignore Yubikey removal, as this is covered by "smd-key-eject".
    exit 0
fi

export PYTHONOPTIMIZE=2
export PYTHONPYCACHEPREFIX="/var/cache/python"

exec /usr/lib/smd/libexec/smd-message --root --translate usb --exit 0 --payload "{\"type\": 1, \"dev\": \"${1}:${2}\"}"
