#!/usr/bin/bash
# smd-auto-display
#  Attempts to determine the monitors connected and will try to use xrandr to auto-add them.
#
# Usage:
# smd-auto-display
#
# System Management Daemon
#
# Copyright (C) 2016 - 2021 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

primary="eDP-1"
connected=$(/usr/bin/xrandr | grep -E ' connected' | awk '{print $1}' | grep -v $primary)
size=$(/usr/bin/xrandr --query | grep $primary | grep -o "[0-9][0-9]*x[0-9][0-9]*" | head -1)

if [ -z "$connected" ] || [ -z "$size" ]; then
    exit 1
fi

index=0
width=$(echo $size | awk -F'x' '{print $1}')
command="/usr/bin/xrandr --output $primary --mode $size --pos 0x0 --rotate normal"

# Prevent CRC failed, turn off all monitors first (except $primary).
for monitor in $connected; do
    command="$command --output $monitor --off"
done
eval "$command"

# Reset command and set monitors.
command="/usr/bin/xrandr --output $primary --mode $size --pos 0x0 --rotate normal"
for monitor in $connected; do
    command="$command --output $monitor --mode $size --pos $(($width*$index))x0 --rotate normal"
    index=$(($index + 1))

    # XRANDR will sometimes fail on mutliple display add, so increment each addition instead.
    eval "$command"
done

eval "$command"
/usr/bin/xrandr --dpi 95x95

if [ $# -ge 1 ]; then
    /usr/lib/smd/libexec/smd-message -u monitor
fi
exit 0
