#!/usr/bin/python3 -X pycache_prefix=/var/cache/python -u -OO
################################
### iDigitalFlame  2016-2026 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
#
# Copyright (C) 2016 - 2026 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# smd-client
#   Entrypoint for the SMD client daemon.
#
# Usage:
#   smd-client [-s socket] [-l log] [-n log_level] [-c config] [-w seconds] [-j] [-r] [-f]
#
#   Starts the system management client. Recommended to be only used by systemd-user
#   or the workspace manager.
#
# Exit Codes:
#   0 - Completed successfully
#   1 - Error occurred or syntax error

# isort please don't lint this
"""
isort:skip_file
"""

import sys

sys.path.insert(0, "/usr/lib/smd")

from os import fork
from time import sleep
from sys import exit, stderr
from argparse import ArgumentParser
from lib import Client, print_error
from lib.constants import VERSION, LOG_LEVELS
from lib.constants.config import SOCKET, LOG_LEVEL, CONFIG_CLIENT, LOG_PATH_CLIENT


HELP_TEXT = """System Management Client (v{version})

User-level service process for the System Management Daemon. This can be ran using
a SystemD user-level daemon or forked in the background.

Usage:
  smd-client [-s socket] [-l log_file] [-n log_level] [-c config] [-w seconds] [-j] [-r] [-f]

Command Line Options:
  -s           <socket>    Path to the SMD control socket to connect to.
  --socket                  Defaults to "{socket}".
  -l           <log_file>  Path to the log output file. Defaults to
  --log                     "{log}".
  -n           <log_level> The log level to use. (The values [0-4] or DEBUG,
  --log-level               INFO, WARNING, ERROR or CRITICAL). Defaults to "{level}".
  -c           <config>    Path to the SMD Client configuration file. Defaults
  --config                  to "{config}".
  -w           <seconds>   Number of seconds to wait before initialization.
  --wait                    Defaults to zero (0).
  -j                       Omit the status values "time" and "name" in console
  --journal                 output. Prevents duplication of these values when
                            running as a SystemD service.
  -r                       Do not write to the configuration file.
  --read-only
  -f                       Do not fork to the background.
  --foreground
"""


def _help(*_):
    print(
        HELP_TEXT.format(
            socket=SOCKET,
            version=VERSION,
            log=LOG_PATH_CLIENT,
            config=CONFIG_CLIENT,
            level=f"{LOG_LEVEL}".upper(),
        ),
        file=stderr,
    )
    exit(2)


def _fork(args):
    if args.fork:
        try:
            if fork() > 0:
                if args.wait > 0:
                    sleep(args.wait)
                return True
        except OSError as err:
            return print_error("Cannot fork to background!", err)
    if args.wait > 0:
        sleep(args.wait)
    return _main(args)


def _main(args):
    try:
        c = Client(
            args.config,
            args.socket,
            args.log_level,
            args.log_file,
            args.read_only,
            args.journal,
        )
    except Exception as err:
        return print_error("Cannot create the Client instance!", err)
    try:
        if not c.start():
            return print_error("Client encountered an error, quitting!", quit=False)
    except KeyboardInterrupt:
        pass
    except Exception as err:
        return print_error("Error during runtime!", err, False)
    finally:
        c.stop()
        del c
    return True


if __name__ == "__main__":
    p = ArgumentParser(description="System Management Client")
    p.add_argument(
        "-s",
        "--socket",
        type=str,
        dest="socket",
        action="store",
        metavar="socket",
        default=SOCKET,
        required=False,
    )
    p.add_argument(
        "-l",
        "--log",
        type=str,
        dest="log_file",
        action="store",
        metavar="log_file",
        default=LOG_PATH_CLIENT,
        required=False,
    )
    p.add_argument(
        "-n",
        "--log-level",
        type=str,
        dest="log_level",
        action="store",
        metavar="log_level",
        default=LOG_LEVEL.lower(),
        choices=LOG_LEVELS.keys(),
        required=False,
    )
    p.add_argument(
        "-c",
        "--config",
        type=str,
        dest="config",
        action="store",
        metavar="config",
        default=CONFIG_CLIENT,
        required=False,
    )
    p.add_argument(
        "-w",
        "--wait",
        type=int,
        dest="wait",
        action="store",
        metavar="wait",
        default=0,
        required=False,
    )
    p.add_argument("-j", "--journal", dest="journal", action="store_true")
    p.add_argument("-f", "--foreground", dest="fork", action="store_false")
    p.add_argument("-r", "--read-only", dest="read_only", action="store_true")
    p.print_help = _help
    if not _fork(p.parse_args()):
        exit(1)
    exit(0)
