#!/usr/bin/dash
# smd-convert-picture
#  Converts a picture given in the arguments to a cache file to be used for the lockscreen.
#  Resizes and applies the gradient for the lockscreen.
#
# Usage:
#  smd-convert-picture <resolution> <source> <destination>
#
# Exit Codes:
#  0 - Conversion completed.
#  1 - Permissions or arguments errors.
#
# System Management Daemon
#
# Copyright (C) 2016 - 2022 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Enable Strict Mode
set -u

if [ $# -ne 3 ]; then
    printf "$0 <resolution> <source> <destination>\n"
    exit 1
fi

hx=$(($(echo "$1" | awk -F'x' '{print $1}')/2))
hy=$(($(echo "$1" | awk -F'x' '{print $2}')/2))

if [ -e "${HOME}/.config/user.ico" ]; then
    ln -s "${HOME}/.config/user.ico" "${HOME}/.cache/smd/user" 2> /dev/null
    cd "${HOME}/.cache/smd"
    convert -quality 100 -resize "$1!" -gravity center \
    -fill "rgb(25,25,25)" \
    -draw "ellipse $((hx)),$((hy)) 100,100 0,360" \
    -draw "image Over 0,0,150,150 user" \
    -fill "rgba(0,0,0,0.5)" -strokewidth 0 \
    -draw "rectangle $((hx-55)),$((hy+115)) $((hx+55)),$((hy+160))" "$2" "$3"
else
    convert -quality 100 -resize "$1!" -gravity center \
    -fill "rgb(25,25,25)" \
    -draw "ellipse $((hx)),$((hy)) 100,100 0,360" \
    -fill "rgba(0,0,0,0.5)" -strokewidth 0 \
    -draw "rectangle $((hx-55)),$((hy+115)) $((hx+55)),$((hy+160))" "$2" "$3"
fi
exit 0
