#!/usr/bin/bash
# smd-reset-display
#  Resets the display to only the built-in monitor (for locking/unlocking purposes).
#
# Usage:
# smd-reset-display [no-alert]
#
# The only paramater is used to not inform the SMD about the change. (This might be handled already, see hibernate-pre)
# Uses xrandr to reset the display to the single built in display (eDP-1).
# Exit code is always 0.
#
# System Management Daemon
#
# Copyright (C) 2016 - 2022 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

primary="eDP-1"
cmdline="/usr/bin/xrandr --output $primary --primary --mode 1920x1080 --pos 0x0 --rotate normal"
for mon in $(/usr/bin/xrandr | grep ' connected' | grep -v '0\+0' | awk '{print $1}' | grep -v 'VIRTUAL' | grep -v $primary); do
    cmdline="$cmdline --output $mon --off "
done

eval "$cmdline"
/usr/bin/xrandr --dpi 95x95

if [ $# -eq 0 ]; then
    /usr/lib/smd/libexec/smd-video
fi
exit 0
