#!/usr/bin/bash
# System Management Daemon - Spaceport
# iDigitalFlame
#
# smd-hibernate-post
#  Script used by systemd after the system resumes from hibernate and starts the post-hibernate process.
#  Should only be called by systemd. Exit code is always 0.

/usr/bin/xset -display :1 dpms force on 2> /dev/null
/usr/lib/smd/libexec/smd-message com.spaceport.sleep -p '{ "state": "post"}'
exit 0
