#!/usr/bin/bash
# System Management Daemon - Spaceport
# iDigitalFlame
#
# smd-power-detached
#  Script used by udev to inform the System Management Daemon that the power adapter was removed.
#  Should only be called by systemd. Exit code is always 0.

/usr/lib/smd/libexec/smd-message com.spaceport.power -p '{ "type": "power", "status": "detached" }'
exit 0
