#!/usr/bin/bash
# System Management Daemon - Spaceport
# iDigitalFlame
#
# smd-enable-tap
#  Uses grep and for loops to enable Tap to Click on all eligible input devices.
#
# Usage:
#  smd-enable-tap
#
#  Does not accept any parameters. Will enable Tap to Click on all supported devices.
#  Exit code is always 0.

for devid in $(xinput list --id-only); do
    devtap=$(xinput list-props $devid | grep "Tapping Enabled (")
    if [ ! -z "$devtap" ]; then
        devtid=$(echo $devtap | awk '{print $4}' | sed -e 's/(//g' | sed -e 's/)//g' | sed -e 's/://g')
        xinput set-prop "$devid" "$devtid" 1
    fi
    devtap=$(xinput list-props $devid | grep "Tapping Drag Enabled (")
    if [ ! -z "$devtap" ]; then
        devtid=$(echo $devtap | awk '{print $5}' | sed -e 's/(//g' | sed -e 's/)//g' | sed -e 's/://g')
        xinput set-prop "$devid" "$devtid" 0
    fi
done
exit 0
