################################
### iDigitalFlame  2016-2026 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
## Intel Video Module Configuration
#
# Copyright (C) 2016 - 2026 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

options i915 disable_display=0 disable_power_well=1 edp_vswing=1 enable_dc=4 enable_dmc_wl=0 enable_dp_mst=1 enable_dpcd_backlight=0 enable_dpt=1 enable_fbc=1 enable_guc=3 enable_gvt=1 enable_hangcheck=1 enable_ips=1 enable_psr2_sel_fetch=1 enable_psr=2 enable_sagv=1 force_reset_modeset_test=0 guc_log_level=0 invert_brightness=0 memtest=0 mitigations="auto" mmio_debug=0 nuclear_pageflip=1 psr_safest_params=0 reset=3 verbose_state_checks=0
