################################
### iDigitalFlame  2016-2026 ###
#                              #
#            -/`               #
#            -yy-   :/`        #
#         ./-shho`:so`         #
#    .:- /syhhhh//hhs` `-`     #
#   :ys-:shhhhhhshhhh.:o- `    #
#   /yhsoshhhhhhhhhhhyho`:/.   #
#   `:yhyshhhhhhhhhhhhhh+hd:   #
#     :yssyhhhhhyhhhhhhhhdd:   #
#    .:.oyshhhyyyhhhhhhddd:    #
#    :o+hhhhhyssyhhdddmmd-     #
#     .+yhhhhyssshdmmddo.      #
#       `///yyysshd++`         #
#                              #
########## SPACEPORT ###########
### Spaceport + SMD
## GUI Cache User Tempfiles Configuration
#
# Copyright (C) 2016 - 2026 iDigitalFlame
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

d  "%t/temp"                                    0750 - - - -
d  "%t/temp/gui"                                0750 - - - -
d  "%t/temp/gui/db"                             0750 - - - -
d  "%t/temp/gui/qt"                             0750 - - - -
d  "%t/temp/gui/gtk"                            0750 - - - -
d  "%t/temp/gui/font"                           0750 - - - -
d  "%t/temp/gui/mesa"                           0750 - - - -

L+ "%C/gtk-2.0"                                 -    - - - %t/temp/gui/gtk
L+ "%C/gtk-3.0"                                 -    - - - %t/temp/gui/gtk
L+ "%C/gtk-4.0"                                 -    - - - %t/temp/gui/gtk
L+ "%C/fontconfig"                              -    - - - %t/temp/gui/font
L+ "%C/mesa_shader_cache"                       -    - - - %t/temp/gui/mesa
L+ "%C/mesa_shader_cache_db"                    -    - - - %t/temp/gui/db
L+ "%C/qtshadercache-x86_64-little_endian-lp64" -    - - - %t/temp/gui/qt
